# Website settings
url: "https://www.ybrikman.com"

# Internal nav
nav:
  main:
    projects: "/projects"
    writing: "/writing"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Andrei Tihoan"
description: "The home page of Yevgeniy (Jim) Brikman, co-founder of Gruntwork, author of &quot;Hello, Startup&quot; and &quot;Terraform: Up & Running&quot;, and software engineer at LinkedIn, TripAdvisor, Cisco Systems, and Thomson Financial."
thumbnail_path: "profile-photos/Andrei-Tihoan-medium-grey.jpg"
bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
hello_startup_url: "https://www.hello-startup.net/"
website_repo_url: "https://github.com/brikis98/yevgeniy-brikman-homepage"
atomic_squirrel_url: "https://www.atomic-squirrel.net/"
gruntwork_url: "https://www.gruntwork.io/"
terraform_up_and_running_url: "https://www.terraformupandrunning.com/"
terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/andrei-tihoan/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/AndreiTih"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:andrei.tihoan0@gmail.com"
    label: "Email"
    value: "andrei.tihoan0@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: brikis98/yevgeniy-brikman-homepage

# Plugins (GitHub Pages only support a few)
plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
