# Website settings
url: "https://www.ybrikman.com"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    photos: "/photos"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Yevgeniy Brikman"
description: "The home page of Yevgeniy (Jim) Brikman, co-founder of Gruntwork, author of &quot;Hello, Startup&quot; and &quot;Terraform: Up & Running&quot;, and software engineer at LinkedIn, TripAdvisor, Cisco Systems, and Thomson Financial."
thumbnail_path: "profile-photos/yevgeniy-brikman-medium.jpg"
bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
hello_startup_url: "https://www.hello-startup.net/"
website_repo_url: "https://github.com/brikis98/yevgeniy-brikman-homepage"
atomic_squirrel_url: "https://www.atomic-squirrel.net/"
gruntwork_url: "https://www.gruntwork.io/"
terraform_up_and_running_url: "https://www.terraformupandrunning.com/"
terraform_up_and_running_code_url: "https://github.com/brikis98/terraform-up-and-running-code"

# URLs
contact_urls:
  twitter:
    url: "https://twitter.com/brikis98"
    label: "Twitter"
    icon: "twitter-square"
    username: "@brikis98"
  linkedin:
    url: "https://www.linkedin.com/in/jbrikman"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/brikis98"
    label: "Facebook"
    icon: "facebook-square"
  google:
    url: "https://plus.google.com/+YevgeniyBrikman/"
    label: "Google+"
    icon: "google-plus-square"
  slideshare:
    url: "https://www.slideshare.net/brikis98"
    label: "SlideShare"
    icon: "slideshare"
  github:
    url: "https://github.com/brikis98/"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:jim@ybrikman.com"
    label: "Email"
    value: "jim@ybrikman.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
repository: brikis98/yevgeniy-brikman-homepage

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
